#!/bin/sh

BRANCH_NAME=$(git branch | grep '*' | sed 's/* //')
if [ $BRANCH_NAME != '(no branch)' ]
then
    echo "#" >> $1
    echo "# Last 20 commit messages" >> $1
    echo "# -----------------------" >> $1
    COMMITS=`git log --pretty=format:"# %h %s [%an]" -20`
    echo "${COMMITS}" >> $1
fi
